name: Deploy app

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: latest

      - name: Authenticate to Fly.io
        run: flyctl auth login --access-token "$FLY_API_TOKEN"

      - name: Deploy to Fly
        run: flyctl deploy --remote-only
